### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by L0garithmic** [dark-knight404/bhaktamarstotra#4]
Just figured this was an easy way to contact you. Could you make me admin or owner or whatever of the DarkThumbs repo. Was gonna make some tweaks, work with a dude who was wanting to tweak some code. Thanks!! Long time no talk lol

**Comment by dark-knight404** [comment]
Hi bro, I was reading the conversation going on in DarkThumbs.
Sorry I couldn't respond.
I've requested for transferring ownership, all you have to do is accept!

**Comment by L0garithmic** [comment]
Thanks! I just wanted to be able to push updates if people made them, I am going to see about making you an admin or whatever.

**Comment by dark-knight404** [comment]
No problem bro!
Yup all good here, hope you're doing good too.
I will try to look into any changes (pull requests) people raise/submit in DarkThumbs.
Only thing I don't have time to recreate/debug/fix the current issue.

**Comment by L0garithmic** [comment]
Totally get it, did not expect you to put any more time into it, I just wanted to make sure I was in a position to work with others if they wanted to put the time in. I didn't want to bother you if someone wanted me to make some changes and if I wanted to update releases, all good. You still THE man lol. Glad you're around!
